title: GoldCopyTrading.com
description: Get consistent growth in low-risk Cents Accounts that exclusively trade Gold (XAUUSD)
baseurl: ""
url: ""

# SEO settings
author: GoldCopyTrading.com
google_analytics: G-JYMV22G2B2
gtm_id: GTM-WQTS4MB9

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap